
import { Location } from './types';

export const INITIAL_LOCATIONS: Location[] = [
  { id: 1, name: "15 Trần Phú, Phường Ba Đình, Hà Nội", address: "15 Trần Phú, Phường Ba Đình, Hà Nội" },
{ id: 2, name: "52 Hàng Đậu, Phường Hoàn Kiếm, Hà Nội", address: "52 Hàng Đậu, Phường Hoàn Kiếm, Hà Nội" },
{ id: 3, name: "126 Phố Huế, Phường Hai Bà Trưng, Hà Nội", address: "126 Phố Huế, Phường Hai Bà Trưng, Hà Nội" },
{ id: 4, name: "194 Lê Duẩn, Phường Văn Miếu - Quốc Tử Giám, Hà Nội", address: "194 Lê Duẩn, Phường Văn Miếu - Quốc Tử Giám, Hà Nội" },
{ id: 5, name: "418 Xã Đàn, Phường Văn Miếu - Quốc Tử Giám, Hà Nội", address: "418 Xã Đàn, Phường Văn Miếu - Quốc Tử Giám, Hà Nội" },
{ id: 6, name: "346 Bạch Mai, Phường Bạch Mai, Hà Nội", address: "346 Bạch Mai, Phường Bạch Mai, Hà Nội" },
{ id: 7, name: "382 Nguyễn Văn Cừ, Phường Bồ Đề, Hà Nội", address: "382 Nguyễn Văn Cừ, Phường Bồ Đề, Hà Nội" },
{ id: 8, name: "101 Kim Mã, Phường Giảng Võ, Hà Nội", address: "101 Kim Mã, Phường Giảng Võ, Hà Nội" },
{ id: 9, name: "89 Tam Trinh, Phường Vĩnh Tuy, Hà Nội", address: "89 Tam Trinh, Phường Vĩnh Tuy, Hà Nội" },
{ id: 10, name: "122 Thái Hà, Phường Đống Đa, Hà Nội", address: "122 Thái Hà, Phường Đống Đa, Hà Nội" },
{ id: 11, name: "392 Trương Định, Phường Tương Mai, Hà Nội", address: "392 Trương Định, Phường Tương Mai, Hà Nội" },
{ id: 12, name: "749 Giải Phóng, Phường Tương Mai, Hà Nội", address: "749 Giải Phóng, Phường Tương Mai, Hà Nội" },
{ id: 13, name: "259 đường Lạc Long Quân, Phường Nghĩa Đô, Hà Nội", address: "259 đường Lạc Long Quân, Phường Nghĩa Đô, Hà Nội" },
{ id: 14, name: "258 Ngô Gia Tự, Phường Việt Hưng, Hà Nội", address: "258 Ngô Gia Tự, Phường Việt Hưng, Hà Nội" },
{ id: 15, name: "330 Nguyễn Trãi, Phường Thanh Xuân, Hà Nội", address: "330 Nguyễn Trãi, Phường Thanh Xuân, Hà Nội" },
{ id: 16, name: "651 Nguyễn Văn Linh, Phường Long Biên, Hà Nội", address: "651 Nguyễn Văn Linh, Phường Long Biên, Hà Nội" },
{ id: 17, name: "109 Trần Duy Hưng, Phường Yên Hòa, Hà Nội", address: "109 Trần Duy Hưng, Phường Yên Hòa, Hà Nội" },
{ id: 18, name: "392 Cầu Giấy, Phường Cầu Giấy, Hà Nội", address: "392 Cầu Giấy, Phường Cầu Giấy, Hà Nội" },
{ id: 19, name: "336 Đường Phạm Văn Đồng, Phường Đông Ngạc, Hà Nội", address: "336 Đường Phạm Văn Đồng, Phường Đông Ngạc, Hà Nội" },
{ id: 20, name: "77 Ngô Xuân Quảng, Xã Gia Lâm, Hà Nội", address: "77 Ngô Xuân Quảng, Xã Gia Lâm, Hà Nội" },
{ id: 21, name: "28 Trần Phú, Phường Hà Đông, Hà Nội", address: "28 Trần Phú, Phường Hà Đông, Hà Nội" },
{ id: 22, name: "372 Hà Huy Tập, Xã Phù Đổng, Hà Nội", address: "372 Hà Huy Tập, Xã Phù Đổng, Hà Nội" },
{ id: 23, name: "110 Cầu Bươu, Phường Thanh Liệt, Hà Nội", address: "110 Cầu Bươu, Phường Thanh Liệt, Hà Nội" },
{ id: 24, name: "348 Hồ Tùng Mậu, Phường Phú Diễn, Hà Nội", address: "348 Hồ Tùng Mậu, Phường Phú Diễn, Hà Nội" },
{ id: 25, name: "123 Vạn Phúc, Phường Hà Đông, Hà Nội", address: "123 Vạn Phúc, Phường Hà Đông, Hà Nội" },
{ id: 26, name: "196 Quang Trung, Phường Hà Đông, Hà Nội", address: "196 Quang Trung, Phường Hà Đông, Hà Nội" },
{ id: 27, name: "182 Cao Lỗ, Xã Đông Anh, Hà Nội", address: "182 Cao Lỗ, Xã Đông Anh, Hà Nội" },
{ id: 28, name: "110 Phố Xốm, Phường Phú Lương, Hà Nội", address: "110 Phố Xốm, Phường Phú Lương, Hà Nội" },
{ id: 29, name: "40 Trần Phú, Phường Từ Sơn, Bắc Ninh", address: "40 Trần Phú, Phường Từ Sơn, Bắc Ninh" },
{ id: 30, name: "Số 484 khu 7, Xã Hoài Đức, Hà Nội", address: "Số 484 khu 7, Xã Hoài Đức, Hà Nội" },
{ id: 31, name: "208 Trần Lư, Xã Thường Tín, Hà Nội", address: "208 Trần Lư, Xã Thường Tín, Hà Nội" },
{ id: 32, name: "Số 2 Phố Nối, Phường Mỹ Hào, Hưng Yên", address: "Số 2 Phố Nối, Phường Mỹ Hào, Hưng Yên" },
{ id: 33, name: "Số 1 Lạc Long Quân, Phường Phúc Yên, Phú Thọ", address: "Số 1 Lạc Long Quân, Phường Phúc Yên, Phú Thọ" },
{ id: 34, name: "258 Ngô Gia Tự, Phường Kinh Bắc, Bắc Ninh", address: "258 Ngô Gia Tự, Phường Kinh Bắc, Bắc Ninh" },
{ id: 35, name: "Số 155, Khu 1, Phường Quế Võ, Bắc Ninh", address: "Số 155, Khu 1, Phường Quế Võ, Bắc Ninh" },
{ id: 36, name: "59 Quang Trung, Xã Vân Đình, Hà Nội", address: "59 Quang Trung, Xã Vân Đình, Hà Nội" },
{ id: 37, name: "176 Chùa Thông, Phường Sơn Tây, Hà Nội", address: "176 Chùa Thông, Phường Sơn Tây, Hà Nội" },
{ id: 38, name: "Số 20 Mê Linh, Phường Vĩnh Phúc, Phú Thọ", address: "Số 20 Mê Linh, Phường Vĩnh Phúc, Phú Thọ" },
{ id: 39, name: "55 Hùng Vương, Phường Bắc Giang, Bắc Ninh", address: "55 Hùng Vương, Phường Bắc Giang, Bắc Ninh" },
{ id: 40, name: "95 Lê Thanh Nghị, Phường Lê Thanh Nghị, Hải Phòng", address: "95 Lê Thanh Nghị, Phường Lê Thanh Nghị, Hải Phòng" },
{ id: 41, name: "Số 222 Đường Lê Hoàn, Phường Phủ Lý, Ninh Bình", address: "Số 222 Đường Lê Hoàn, Phường Phủ Lý, Ninh Bình" },
{ id: 42, name: "479-481 Cù Chính Lan, Phường Hòa Bình, Phú Thọ", address: "479-481 Cù Chính Lan, Phường Hòa Bình, Phú Thọ" },
{ id: 43, name: "2253 Đại Lộ Hùng Vương, Phường Nông Trang, Phú Thọ", address: "2253 Đại Lộ Hùng Vương, Phường Nông Trang, Phú Thọ" },
{ id: 44, name: "378 Lương Ngọc Quyến, Phường Phan Đình Phùng, Thái Nguyên", address: "378 Lương Ngọc Quyến, Phường Phan Đình Phùng, Thái Nguyên" },
{ id: 45, name: "Số 4 Thành Chung, Phường Nam Định, Ninh Bình", address: "Số 4 Thành Chung, Phường Nam Định, Ninh Bình" },
{ id: 46, name: "390 Lý Bôn, Phường Thái Bình, Hưng Yên", address: "390 Lý Bôn, Phường Thái Bình, Hưng Yên" },
{ id: 47, name: "67 Bạch Đằng, Phường Thuỷ Nguyên, Hải Phòng", address: "67 Bạch Đằng, Phường Thuỷ Nguyên, Hải Phòng" },
{ id: 48, name: "147 Đà Nẵng, Phường Ngô Quyền, Hải Phòng", address: "147 Đà Nẵng, Phường Ngô Quyền, Hải Phòng" },
{ id: 49, name: "960 Trần Hưng Đạo, Phường Hoa Lư, Ninh Bình", address: "960 Trần Hưng Đạo, Phường Hoa Lư, Ninh Bình" },
{ id: 50, name: "Số 258 Đường Tô Hiệu, Phường Lê Chân, Hải Phòng", address: "Số 258 Đường Tô Hiệu, Phường Lê Chân, Hải Phòng" },
{ id: 51, name: "39 Lạch Tray, Phường Gia Viên, Hải Phòng", address: "39 Lạch Tray, Phường Gia Viên, Hải Phòng" },
{ id: 52, name: "370 Quang Trung, Phường Uông Bí, Quảng Ninh", address: "370 Quang Trung, Phường Uông Bí, Quảng Ninh" },
{ id: 53, name: "447-449 Quang Trung, Phường Minh Xuân, Tuyên Quang", address: "447-449 Quang Trung, Phường Minh Xuân, Tuyên Quang" },
{ id: 54, name: "561B đường Hạ Long, Phường Bãi Cháy, Quảng Ninh", address: "561B đường Hạ Long, Phường Bãi Cháy, Quảng Ninh" },
{ id: 55, name: "24 Nguyễn Thái Học, Phường Yên Bái, Lào Cai", address: "24 Nguyễn Thái Học, Phường Yên Bái, Lào Cai" },
{ id: 56, name: "Số 68 Kênh Liêm, Phường Hà Lầm, Quảng Ninh", address: "Số 68 Kênh Liêm, Phường Hà Lầm, Quảng Ninh" },
{ id: 57, name: "222 Trần Phú, Phường Hạc Thành, Thanh Hóa", address: "222 Trần Phú, Phường Hạc Thành, Thanh Hóa" },
{ id: 58, name: "306 Nguyễn Trãi, Phường Hạc Thành, Thanh Hóa", address: "306 Nguyễn Trãi, Phường Hạc Thành, Thanh Hóa" },
{ id: 59, name: "451A Trần Phú, Phường Cẩm Phả, Quảng Ninh", address: "451A Trần Phú, Phường Cẩm Phả, Quảng Ninh" },
{ id: 60, name: "130 Chu Văn Thịnh, Phường Tô Hiệu, Sơn La", address: "130 Chu Văn Thịnh, Phường Tô Hiệu, Sơn La" },
{ id: 61, name: "Lô 10 - Ngã 6 Đường Lý Công Uẩn, Phường Lào Cai, Lào Cai", address: "Lô 10 - Ngã 6 Đường Lý Công Uẩn, Phường Lào Cai, Lào Cai" },
{ id: 62, name: "Số 34 Nguyễn Sỹ Sách, Phường Thành Vinh, Nghệ An", address: "Số 34 Nguyễn Sỹ Sách, Phường Thành Vinh, Nghệ An" },
{ id: 63, name: "10 Nguyễn Thị Minh Khai, Phường Thành Vinh, Nghệ An", address: "10 Nguyễn Thị Minh Khai, Phường Thành Vinh, Nghệ An" },
{ id: 64, name: "896 Đường Võ Nguyên Giáp, Phường Điện Biên Phủ, Điện Biên", address: "896 Đường Võ Nguyên Giáp, Phường Điện Biên Phủ, Điện Biên" },
{ id: 65, name: "Số 161 đường Trần Phú, Phường Thành Sen, Hà Tĩnh", address: "Số 161 đường Trần Phú, Phường Thành Sen, Hà Tĩnh" },
{ id: 66, name: "Số 96 Trần Hưng Đạo, Phường Đồng Hới, Quảng Trị", address: "Số 96 Trần Hưng Đạo, Phường Đồng Hới, Quảng Trị" },
{ id: 67, name: "139 Quốc Lộ 9, Phường Nam Đông Hà, Quảng Trị", address: "139 Quốc Lộ 9, Phường Nam Đông Hà, Quảng Trị" },
{ id: 68, name: "48 Đống Đa, Phường Thuận Hóa, Huế", address: "48 Đống Đa, Phường Thuận Hóa, Huế" },
{ id: 69, name: "460-462 Đường Tôn Đức Thắng, Phường Hòa Khánh, Đà Nẵng", address: "460-462 Đường Tôn Đức Thắng, Phường Hòa Khánh, Đà Nẵng" },
{ id: 70, name: "580-582 Điện Biên Phủ, Phường Thanh Khê, Đà Nẵng", address: "580-582 Điện Biên Phủ, Phường Thanh Khê, Đà Nẵng" },
{ id: 71, name: "153-155 Nguyễn Văn Linh, Phường Hải Châu, Đà Nẵng", address: "153-155 Nguyễn Văn Linh, Phường Hải Châu, Đà Nẵng" },
{ id: 72, name: "225 Phan Châu Trinh, Phường Tam Kỳ, Đà Nẵng", address: "225 Phan Châu Trinh, Phường Tam Kỳ, Đà Nẵng" },
{ id: 73, name: "222 Quang Trung, Phường Nghĩa Lộ, Quảng Ngãi", address: "222 Quang Trung, Phường Nghĩa Lộ, Quảng Ngãi" },
{ id: 74, name: "33 Trần Phú, Phường Pleiku, Gia Lai", address: "33 Trần Phú, Phường Pleiku, Gia Lai" },
{ id: 75, name: "232 Nguyễn Thái Học, Phường Quy Nhơn Nam, Gia Lai", address: "232 Nguyễn Thái Học, Phường Quy Nhơn Nam, Gia Lai" },
{ id: 76, name: "190-192 Tăng Bạt Hổ, Phường Quy Nhơn, Gia Lai", address: "190-192 Tăng Bạt Hổ, Phường Quy Nhơn, Gia Lai" },
{ id: 77, name: "335 Nguyễn Huệ, Phường Tuy Hòa, Đắk Lắk", address: "335 Nguyễn Huệ, Phường Tuy Hòa, Đắk Lắk" },
{ id: 78, name: "07–09 Phan Bội Châu, Phường Buôn Ma Thuột, Đắk Lắk", address: "07–09 Phan Bội Châu, Phường Buôn Ma Thuột, Đắk Lắk" },
{ id: 79, name: "404 Lê Duẩn, Phường Ea Kao, Đắk Lắk", address: "404 Lê Duẩn, Phường Ea Kao, Đắk Lắk" },
{ id: 80, name: "Số 204A Đường Huỳnh Thúc Kháng, Phường Bắc Gia Nghĩa, Lâm Đồng", address: "Số 204A Đường Huỳnh Thúc Kháng, Phường Bắc Gia Nghĩa, Lâm Đồng" },
{ id: 81, name: "580 đường 2 tháng 4, Phường Bắc Nha Trang, Khánh Hòa", address: "580 đường 2 tháng 4, Phường Bắc Nha Trang, Khánh Hòa" },
{ id: 82, name: "61A Quang Trung, Phường Bắc Nha Trang, Khánh Hòa", address: "61A Quang Trung, Phường Bắc Nha Trang, Khánh Hòa" },
{ id: 83, name: "310 Bùi Thị Xuân, Phường Xuân Hương - Đà Lạt, Lâm Đồng", address: "310 Bùi Thị Xuân, Phường Xuân Hương - Đà Lạt, Lâm Đồng" },
{ id: 84, name: "1039 Phú Riềng Đỏ, Phường Bình Phước, Đồng Nai", address: "1039 Phú Riềng Đỏ, Phường Bình Phước, Đồng Nai" },
{ id: 85, name: "585 Cách Mạng Tháng 8, Phường Tân Ninh, Tây Ninh", address: "585 Cách Mạng Tháng 8, Phường Tân Ninh, Tây Ninh" },
{ id: 86, name: "22 Đường 16 Tháng 4, Phường Phan Rang, Khánh Hòa", address: "22 Đường 16 Tháng 4, Phường Phan Rang, Khánh Hòa" },
{ id: 87, name: "499 Đường Phú Lợi, Phường Phú Lợi, Hồ Chí Minh", address: "499 Đường Phú Lợi, Phường Phú Lợi, Hồ Chí Minh" },
{ id: 88, name: "272 Đại Lộ Bình Dương, Phường Thủ Dầu Một, Hồ Chí Minh", address: "272 Đại Lộ Bình Dương, Phường Thủ Dầu Một, Hồ Chí Minh" },
{ id: 89, name: "92 Nguyễn Ái Quốc - Khu Phố 8A, Phường Long Bình, Đồng Nai", address: "92 Nguyễn Ái Quốc - Khu Phố 8A, Phường Long Bình, Đồng Nai" },
{ id: 90, name: "690-692 Phạm Văn Thuận, Phường Tam Hiệp, Đồng Nai", address: "690-692 Phạm Văn Thuận, Phường Tam Hiệp, Đồng Nai" },
{ id: 91, name: "108 Nguyễn Văn Tiết, Phường Lái Thiêu, Hồ Chí Minh", address: "108 Nguyễn Văn Tiết, Phường Lái Thiêu, Hồ Chí Minh" },
{ id: 92, name: "72A Nguyễn An Ninh, Phường Dĩ An, Hồ Chí Minh", address: "72A Nguyễn An Ninh, Phường Dĩ An, Hồ Chí Minh" },
{ id: 93, name: "260 đường Hùng Vương, Phường Long Khánh, Đồng Nai", address: "260 đường Hùng Vương, Phường Long Khánh, Đồng Nai" },
{ id: 94, name: "419 Nguyễn Ảnh Thủ, Phường Trung Mỹ Tây, Hồ Chí Minh", address: "419 Nguyễn Ảnh Thủ, Phường Trung Mỹ Tây, Hồ Chí Minh" },
{ id: 95, name: "Số 127 Tô Ngọc Vân, Phường Thủ Đức, Hồ Chí Minh", address: "Số 127 Tô Ngọc Vân, Phường Thủ Đức, Hồ Chí Minh" },
{ id: 96, name: "Số 454 Nguyễn Oanh, Phường An Nhơn, Hồ Chí Minh", address: "Số 454 Nguyễn Oanh, Phường An Nhơn, Hồ Chí Minh" },
{ id: 97, name: "Số 215 Lê Văn Việt, Phường Tăng Nhơn Phú, Hồ Chí Minh", address: "Số 215 Lê Văn Việt, Phường Tăng Nhơn Phú, Hồ Chí Minh" },
{ id: 98, name: "436 Quang Trung, Phường Gò Vấp, Hồ Chí Minh", address: "436 Quang Trung, Phường Gò Vấp, Hồ Chí Minh" },
{ id: 99, name: "397 Nguyễn Thị Tú, Phường Bình Tân, Hồ Chí Minh", address: "397 Nguyễn Thị Tú, Phường Bình Tân, Hồ Chí Minh" },
{ id: 100, name: "Số 489B Đỗ Xuân Hợp, Phường Phước Long, Hồ Chí Minh", address: "Số 489B Đỗ Xuân Hợp, Phường Phước Long, Hồ Chí Minh" },
{ id: 101, name: "347 Hoàng Văn Thụ, Phường Tân Sơn Hòa, Hồ Chí Minh", address: "347 Hoàng Văn Thụ, Phường Tân Sơn Hòa, Hồ Chí Minh" },
{ id: 102, name: "243 Bạch Đằng, Phường Gia Định, Hồ Chí Minh", address: "243 Bạch Đằng, Phường Gia Định, Hồ Chí Minh" },
{ id: 103, name: "867 Lũy Bán Bích, Phường Tân Phú, Hồ Chí Minh", address: "867 Lũy Bán Bích, Phường Tân Phú, Hồ Chí Minh" },
{ id: 104, name: "188Ter Trần Quang Khải, Phường Tân Định, Hồ Chí Minh", address: "188Ter Trần Quang Khải, Phường Tân Định, Hồ Chí Minh" },
{ id: 105, name: "621D Cách Mạng Tháng 8, Phường Hòa Hưng, Hồ Chí Minh", address: "621D Cách Mạng Tháng 8, Phường Hòa Hưng, Hồ Chí Minh" },
{ id: 106, name: "505 Lê Hồng Phong, Phường Vườn Lài, Hồ Chí Minh", address: "505 Lê Hồng Phong, Phường Vườn Lài, Hồ Chí Minh" },
{ id: 107, name: "1060 Đường 3/2, Phường Phú Thọ, Hồ Chí Minh", address: "1060 Đường 3/2, Phường Phú Thọ, Hồ Chí Minh" },
{ id: 108, name: "572-574 Tỉnh Lộ 10, Phường Bình Trị Đông, Hồ Chí Minh", address: "572-574 Tỉnh Lộ 10, Phường Bình Trị Đông, Hồ Chí Minh" },
{ id: 109, name: "Số 267 Lê Duẩn Khu Phước Hải, Xã Long Thành, Đồng Nai", address: "Số 267 Lê Duẩn Khu Phước Hải, Xã Long Thành, Đồng Nai" },
{ id: 110, name: "Số 254 Khánh Hội, Phường Khánh Hội, Hồ Chí Minh", address: "Số 254 Khánh Hội, Phường Khánh Hội, Hồ Chí Minh" },
{ id: 111, name: "736 Hậu Giang, Phường Phú Lâm, Hồ Chí Minh", address: "736 Hậu Giang, Phường Phú Lâm, Hồ Chí Minh" },
{ id: 112, name: "168 Trần Hưng Đạo, Phường Phú Thuỷ, Lâm Đồng", address: "168 Trần Hưng Đạo, Phường Phú Thuỷ, Lâm Đồng" },
{ id: 113, name: "Số 418 Nguyễn Thị Thập, Phường Tân Hưng, Hồ Chí Minh", address: "Số 418 Nguyễn Thị Thập, Phường Tân Hưng, Hồ Chí Minh" },
{ id: 114, name: "304 Hùng Vương, Phường Long An, Tây Ninh", address: "304 Hùng Vương, Phường Long An, Tây Ninh" },
{ id: 115, name: "85 Nguyễn Huệ, Phường Cao Lãnh, Đồng Tháp", address: "85 Nguyễn Huệ, Phường Cao Lãnh, Đồng Tháp" },
{ id: 116, name: "148 Nguyễn Thanh Đằng, Phường Bà Rịa, Hồ Chí Minh", address: "148 Nguyễn Thanh Đằng, Phường Bà Rịa, Hồ Chí Minh" },
{ id: 117, name: "1456 Trần Hưng Đạo, Phường Long Xuyên, An Giang", address: "1456 Trần Hưng Đạo, Phường Long Xuyên, An Giang" },
{ id: 118, name: "29-31 Nguyễn Trãi, Phường Mỹ Tho, Đồng Tháp", address: "29-31 Nguyễn Trãi, Phường Mỹ Tho, Đồng Tháp" },
{ id: 119, name: "631 đường 30 Tháng 4, Phường Rạch Dừa, Hồ Chí Minh", address: "631 đường 30 Tháng 4, Phường Rạch Dừa, Hồ Chí Minh" },
{ id: 120, name: "91 Ba Cu, Phường Vũng Tàu, Hồ Chí Minh", address: "91 Ba Cu, Phường Vũng Tàu, Hồ Chí Minh" },
{ id: 121, name: "134 Trưng Nữ Vương, Phường Long Châu, Vĩnh Long", address: "134 Trưng Nữ Vương, Phường Long Châu, Vĩnh Long" },
{ id: 122, name: "231A đường 3/2, Phường Tân An, Cần Thơ", address: "231A đường 3/2, Phường Tân An, Cần Thơ" },
{ id: 123, name: "148 Nguyễn Trung Trực, Phường Rạch Giá, An Giang", address: "148 Nguyễn Trung Trực, Phường Rạch Giá, An Giang" },
{ id: 124, name: "174 Mạc Đĩnh Chi, Phường Phú Lợi, Cần Thơ", address: "174 Mạc Đĩnh Chi, Phường Phú Lợi, Cần Thơ" },
{ id: 125, name: "182 Trần Phú, Phường Bạc Liêu, Cà Mau", address: "182 Trần Phú, Phường Bạc Liêu, Cà Mau" },
{ id: 126, name: "04 Trần Hưng Đạo, Phường Vĩnh Trạch, Cà Mau", address: "04 Trần Hưng Đạo, Phường Vĩnh Trạch, Cà Mau" }
];
